services:
  postgres:
    container_name: postgres_container_bsn
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-username}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - book-social-network
    restart: unless-stopped

  mail-dev:
    image: maildev/maildev
    container_name: maildev_bsn
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - book-social-network

  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak_bsn
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - book-social-network
    command:
      - "start-dev"



networks:
  book-social-network:
    driver: bridge

volumes:
  postgres:
    driver: local