services:
  postgres:
    container_name: postgres_container_bsn
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-username}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  mail-dev:
    image: maildev/maildev
    container_name: maildev_bsn
    ports:
      - 1080:1080
      - 1025:1025



networks:
  postgres:
    driver: bridge

volumes:
  postgres:
    driver: local